extend type Query {
    payments(workspaceId: Int): [Payment!]!
        @field(resolver: "Payment\\PaymentsQuery")
    payment(id: ID!, workspaceId: Int @eq): Payment
        @field(resolver: "Payment\\PaymentQuery")

    # paymentRecord query
    paymentRecords(
        klase_id: Int!
        session_id: Int!
        term_id: Int!
        workspaceId: Int
    ): [PaymentRecord!]! @field(resolver: "Payment\\PaymentRecordsQuery")

    paidPaymentRecords(
        klase_id: Int!
        session_id: Int!
        term_id: Int!
        workspaceId: Int
    ): [PaymentRecord!]! @field(resolver: "Payment\\PaidPaymentRecordsQuery")

    # student


    allDuePaymentRecords(
        workspaceId: Int
        search: String @rules(apply: ["nullable"])
    ): [PaymentRecord!]!
    @paginate(builder: "App\\GraphQL\\Queries\\Payment\\AllDuePaymentRecordsQuery@payments")

    studentPaymentRecords(
      student_id: Int
       session_id: Int!
        term_id: Int!
        klase_id: Int
        workspaceId: Int
        status: String! @eq
    ): PaymentRecord @field(resolver: "Payment\\DueStudentPaymentRecords")
}

extend type Mutation {
    createPayment(
        amount: Int @rules(apply: ["required"])
        klase: String!
        term_id: Int!
        session_id: Int!
        workspaceId: Int
    ): Payment @field(resolver: "Payment\\CreatePaymentMutator")

    updatePayment(
        id: ID!
        workspaceId: Int
        amount: Int @rules(apply: ["required"])
    ): Payment @field(resolver: "Payment\\UpdatePaymentMutator")

    # paymentRecord
    createPaymentRecord(
        id: ID!
        workspaceId: Int
        amt_paid: Int!
    ): PaymentRecord @field(resolver: "Payment\\CreatePaymentRecordMutator")

    resetPaymentRecord(id: ID!, workspaceId: Int): PaymentRecord
        @field(resolver: "Payment\\ResetPaymentRecordMutator")

    CreateStudentPayment(
        student_id: Int!
        session_id: Int!
        term_id: Int!
        amt_paid: Int!
        workspaceId: Int
    ): PaymentRecord @field(resolver: "Payment\\StudentPaymentMutator")
}
