input UsersInput {
    country: String! @rules(apply: ["required"])
    state: String! @rules(apply: ["required"])
    city: String! @rules(apply: ["required"])
    email: String @rules(apply: ["required", "unique:users,email"])
    lga: String @rules(apply: ["required"])
    bloodGroup: String
    religion: String @rules(apply: ["required"])
}

input EditUsersInput {
    country: String! @rules(apply: ["required"])
    state: String! @rules(apply: ["required"])
    city: String! @rules(apply: ["required"])
    email: String @rules(apply: ["required"])
    lga: String @rules(apply: ["required"])
    bloodGroup: String
    religion: String @rules(apply: ["required"])
}


input WorkersInput {
    first_name: String! @rules(apply: ["required"])
    last_name: String! @rules(apply: ["required"])
    middle_name: String
    gender: String! @rules(apply: ["required"])
    photo: Upload
        @rules(apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"])
    image: Upload
        @rules(apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"])
    birthday: String @rules(apply: ["required"])
    phone: String @rules(apply: ["required"])
    employment: String
    qualification: String @rules(apply: ["required"])
}

# student
input StudentUserInput {
    country: String!
    state: String!
    city: String!
    lga: String @rules(apply: ["required"])
    email: String @rules(apply: ["required", "unique:users,email"])
    bloodGroup: String
    religion: String @rules(apply: ["required"])
}

input StudentInput {
    first_name: String! @rules(apply: ["required"])
    last_name: String! @rules(apply: ["required"])
    middle_name: String
    gender: String! @rules(apply: ["required"])
    birthday: String @rules(apply: ["required"])
    phone: String @rules(apply: ["required", "unique:students,phone"])
    klase: String @rules(apply: ["required"])
    address: String @rules(apply: ["required"])
    photo: Upload
        @rules(apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"])
    guardian_name: String @rules(apply: ["required"])
    guardian_no: String @rules(apply: ["required"])
    guardian_email: String @rules(apply: ["required"])
    guardian_address: String @rules(apply: ["required"])
    adm_no: String @rules(apply: ["required", "unique:students,adm_no"])
    term: String @rules(apply: ["required"])
    section: String @rules(apply: ["required"])
    session: String @rules(apply: ["required"])
    admitted_year: String @rules(apply: ["required"])
}

# edit student
input EditStudentUserInput {
    country: String @rules(apply: ["required"])
    state: String @rules(apply: ["required"])
    city: String @rules(apply: ["required"])
    lga: String @rules(apply: ["required"])
    email: String @rules(apply: ["required"])
    bloodGroup: String
    religion: String @rules(apply: ["required"])
}

input EditStudentInput {
    first_name: String! @rules(apply: ["required"])
    last_name: String! @rules(apply: ["required"])
    middle_name: String
    gender: String! @rules(apply: ["required"])
    birthday: String @rules(apply: ["required"])
    phone: String @rules(apply: ["required"])
    klase: String @rules(apply: ["required"])
    address: String @rules(apply: ["required"])
    image: Upload
        @rules(apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"])
    guardian_name: String @rules(apply: ["required"])
    guardian_no: String @rules(apply: ["required"])
    guardian_email: String @rules(apply: ["required"])
    guardian_address: String @rules(apply: ["required"])
    adm_no: String @rules(apply: ["required"])
    term: String @rules(apply: ["required"])
    section: String @rules(apply: ["required"])
    session: String @rules(apply: ["required"])
    admitted_year: String @rules(apply: ["required"])
}

# marks
input MarkInput {
    markId: String
    ca1: String
    ca2: String
    exam: String
}

# attendance
input AttendanceInput {
    classAttendanceId: String
    num_present: String
}
