type User {
    id: ID!
    first_name: String
    last_name: String
    middle_name: String
    user_type: String
    phone: String
    gender: String
    religion: String
    photo: String
    email: String
    city: String
    lga: String
    password: String
    created_at: DateTime
    updated_at: DateTime
    # createdAt: DateTime! @rename(attribute: "created_at")
    roles: [Role]
    permissions: [Permission]
    notifications: [Notification]
    unreadNotifications: [UnreadNotification]
    country: Country @belongsTo
    state: State @belongsTo
    # city: City @belongsTo
    blood_group: BloodGroup @belongsTo
    student: Student @hasOne
    teacher: Teacher @hasOne
    guardian: Guardian @hasOne
    accountant: Accountant @hasOne
    schoolAdmin: SchoolAdmin @hasOne
    workspace: Workspace
}

type Role {
    id: Int!
    name: String!
    permissions: [Permission] @belongsToMany
}

type Permission {
    id: Int!
    name: String!
}

# notification
type Notification {
    id: ID
    type: String
    notifiable_id: Int
    data: Data
    read_at: String
    created_at: String
}

type UnreadNotification {
    type: String
    read_at: String
}
type Data {
    description: String
    workspace_id: Int
}

type Country {
    id: ID!
    name: String
    state: [State] @hasMany
}
type State {
    id: ID!
    name: String
    cities: [City] @hasMany
}
type City {
    id: ID!
    name: String
}
type BloodGroup {
    id: ID!
    name: String
}

type Event {
    id: ID!
    slug: String
    description: String!
    date: String!
    status: Boolean
}
type Notice {
    id: ID!
    slug: String
    description: String!
    date: String!
    status: Boolean
}

type SchoolAdmin {
    id: ID!
    slug: String
    first_name: String!
    last_name: String!
    gender: String!
    birthday: String
    code: String
    middle_name: String
    photo: String
    phone: String
    qualification: String
    user: User @belongsTo
}

type Student {
    id: ID!
    slug: String
    adm_no: String
    code: String!
    admitted_year: String
    birthday: String
    status: Boolean
    first_name: String
    last_name: String!
    gender: String!
    middle_name: String
    address: String!
    phone: String
    photo: String
    photoData: String
    cum_avg: Int
    promotion_term_id: Int
    guardian_name: String
    guardian_no: String
    guardian_email: String
    guardian_address: String
    term: Term @belongsTo
    session: Session @belongsTo
    section: Section @belongsTo
    klase: Klase @belongsTo
    user: User @belongsTo
    guardian: Guardian @belongsTo
}
type Teacher {
    id: ID!
    slug: String
    first_name: String!
    last_name: String!
    gender: String!
    birthday: String
    code: String
    middle_name: String
    photo: String
    phone: String
    qualification: String
    employment: String
    user: User @belongsTo
}

type Accountant {
    id: ID!
    slug: String
    first_name: String!
    last_name: String!
    gender: String!
    birthday: String
    code: String
    middle_name: String
    photo: String
    phone: String
    employment: String
    qualification: String
    user: User @belongsTo
}

type Guardian {
    id: ID!
    slug: String
    email: String
    students: [Student] @hasMany
    user: User @belongsTo
}
type Klase {
    id: ID!
    slug: String
    name: String!
    students: [Student] @hasMany
}
type Subject {
    id: ID!
    subject: String!
    subject_code: String!
    section: Section @belongsTo
    klase: Klase @belongsTo
}
type Timetable {
    id: ID!
    monday: String
    tuesday: String
    wednesday: String
    thursday: String
    friday: String
    time: String
    klase_id: Int!
    section_id: Int!
}
type ExamTimetable {
    id: ID!
    monday: String
    tuesday: String
    wednesday: String
    thursday: String
    friday: String
    time: String
    date: String
    klase_id: Int!
    section_id: Int!
}

type Mark {
    id: ID!
    ca1: Int
    ca2: Int
    tca: Int
    exam: Int
    status: String
    exam_total: Int
    sub_position: Int
    cum_ave: String
    cum: Int
    student: Student @belongsTo
    subject: Subject @belongsTo
    klase: Klase @belongsTo
    grade: Grade @belongsTo
    section: Section @belongsTo
    session: Session @belongsTo
    term: Term @belongsTo
}

type Grade {
    id: ID!
    name: String
    mark_from: Int
    mark_to: Int
    remark: String
}

type Term {
    id: ID!
    name: String
}

type Session {
    id: ID!
    name: String
}
type Section {
    id: ID!
    name: String!
    klase: Klase @belongsTo
}

type ExamRecord {
    id: ID!
    total: Int
    avg: String
    cum_total: String
    cum_avg: String
    klase_avg: String
    position: Int
    cum_position: Int
    status: String
    num_present: Int
    num_absent: Int
    num_total: Int
    term_start: String
    term_end: String
    promoted_to: String
    p_comment: String
    t_comment: String
    ps: String
    subject: Subject @belongsTo
    student: Student @belongsTo
    klase: Klase @belongsTo
    term: Term @belongsTo
    session: Session @belongsTo
    section: Section @belongsTo
}
type SetPromotion {
    id: ID!
    name: Int
}

type Promotion {
    id: ID!
    from_class: Int!
    to_class: Int!
    from_session: Int!
    to_session: Int!
    from_term: Int
    to_term: Int
    status: Boolean!
    student: Student @belongsTo
}

type Payment {
    id: ID!
    title: String
    amount: Int!
    ref_no: String
    method: String
    description: String
    klase: Klase @belongsTo
    term: Term @belongsTo
    session: Session @belongsTo
}

type PaymentRecord {
    id: ID!
    amount: Int!
    ref_no: String
    amt_paid: Int
    balance: Int
    status: String
    receipt: Int
    title: String
    klase: Klase @belongsTo
    term: Term @belongsTo
    session: Session @belongsTo
    payment: Payment @belongsTo
    student: Student @belongsTo
    created_at: DateTime
}

type Workspace {
    id: ID!
    slug: String
    email: String!
    name: String!
    logo: String
    stamp: String
    photo: String
    gender: String
    bank: String
    account_name: String
    account_no: String
    status: Int
    paystack_secret_key: String
    numstudent: Numstudent @belongsTo
    user: User @hasOne
}

type Numstudent {
    id: ID!
    name: String
    count: Int
}

type AssignSubjectTeacher {
    id: ID!
    klase: Klase @belongsTo
    section: Section @belongsTo
    teacher: Teacher @belongsTo
    subject: Subject @belongsTo
}

type EncodedImage {
    id: Int
    studentId: Int
    photoBase64: String
    logoBase64: String
    stampBase64: String
}
