extend type Query {
    accountants: [Accountant!]! @all
    accountant(slug: String! @eq): Accountant @first
}

extend type Mutation {
    createAccountant(
        first_name: String!
        last_name: String!
        gender: String!
        email: String!
        country: Int!
        state: Int!
        city: Int!
        lga: String
        middle_name: String
        photo: Upload
        phone: String
        facebook: String
        qualification: String
        blood_group: Int
        religion: String
    ): Accountant @field(resolver: "Accountant\\CreateAccountantMutator")

    updateAccountant(
        id: ID!
        first_name: String!
        last_name: String!
        gender: String!
        email: String!
        country: Int!
        state: Int!
        city: Int!
        lga: String
        middle_name: String
        photo: Upload
        phone: String
        facebook: String
        qualification: String
        blood_group: Int
        religion: String
    ): Accountant @field(resolver: "Accountant\\UpdateAccountantMutator")
}
