extend type Query {
    accountants(workspaceId: Int): [Accountant!]!
        @field(resolver: "Accountant\\AccountantsQuery")
    accountant(id: ID!, workspaceId: Int @eq): Accountant
        @field(resolver: "Accountant\\AccountantQuery")
}

extend type Mutation {
    createAccountant(
        workspaceId: Int
        userTable: UsersInput
        teacherTable: WorkersInput
    ): Accountant @field(resolver: "Accountant\\CreateAccountantMutator")

    updateAccountant(
        id: ID!
        workspaceId: Int
        userTable: EditUsersInput
        teacherTable: WorkersInput
    ): Accountant @field(resolver: "Accountant\\UpdateAccountantMutator")

    deleteAccountant(
        id: Int! @rules(apply: ["exists:accountants"])
        workspaceId: Int
    ): Boolean @field(resolver: "Accountant\\DeleteAccountantMutator")
}
