extend type Query {
    events(workspaceId: Int! @eq): [Event!]! @field(resolver: "Event\\EventsQuery")

    event(id: ID! @eq): Event @find
}

extend type Mutation {
    createEvent(
        description: String!
        title: String
        photo: Upload
        date: String!
        workspaceId: Int!
    ): Event @field(resolver: "Event\\CreateEventMutator")

    updateEvent(
        id: ID!
        description: String!
        title: String
        photo: Upload
        date: String!
        workspaceId: Int!
    ): Event @field(resolver: "Event\\UpdateEventMutator")

    deleteEvent(id: Int!, workspaceId: Int!): Event
        @field(resolver: "Event\\DeleteEventMutator")

    publishEvent(id: Int!, workspaceId: Int!): Event
        @field(resolver: "Event\\PublishEventMutator")
}
