extend type Query {
    examTimetables(
        klase_id: Int!
        section_id: Int!
        workspaceId: Int
    ): [ExamTimetable!]! @field(resolver: "ExamTimetable\\ExamTimetablesQuery")

    examTimetable(id: ID!, workspaceId: Int): ExamTimetable
        @field(resolver: "ExamTimetable\\ExamTimetableQuery")
}

extend type Mutation {
    createExamTimetable(
        monday: String
        tuesday: String
        wednesday: String
        thursday: String
        friday: String
        time: String
        date: String
        klase_id: Int!
        section_id: Int!
        workspaceId: Int
    ): ExamTimetable
        @field(resolver: "ExamTimetable\\CreateExamTimetableMutator")

    updateExamTimetable(
        id: ID!
        monday: String
        tuesday: String
        wednesday: String
        thursday: String
        friday: String
        time: String
        date: String
        klase_id: Int!
        workspaceId: Int
    ): ExamTimetable
        @field(resolver: "ExamTimetable\\UpdateExamTimetableMutator")

    deleteExamTimetable(id: ID!, workspaceId: Int): ExamTimetable
        @field(resolver: "ExamTimetable\\DeleteExamTimetableMutator")
}
