extend type Query {
    # admin
    examRecords(klase_id: Int!, session_id: Int!): [ExamRecord]
        @field(resolver: "ExamRecord\\ExamRecordsQuery")

    # tabulation sheet
    klaseResults(klase_id: Int!, term_id: Int!, session_id: Int!): [ExamRecord]
        @field(resolver: "ExamRecord\\klaseResultsQuery")

    studentExamResult(
        klase_id: Int!
        term_id: Int!
        student_id: Int!
        session_id: Int!
    ): [ExamRecord] @field(resolver: "ExamRecord\\StudentExamResultQuery")

    firstTerm(klase_id: Int!, term_id: Int!, session_id: Int!): [ExamRecord]
        @field(resolver: "ExamRecord\\FirstTermExamResultQuery")

    secoundTerm(klase_id: Int!, term_id: Int!, session_id: Int!): [ExamRecord]
        @field(resolver: "ExamRecord\\SecoundTermExamResultQuery")

    thirdTerm(klase_id: Int!, term_id: Int!, session_id: Int!): [ExamRecord]
        @field(resolver: "ExamRecord\\ThirdTermExamResultQuery")

    # publish result
    publishResult(
        klase_id: Int!
        term_id: Int!
        session_id: Int!
        status: String!
    ): ExamRecord @field(resolver: "ExamRecord\\PublishResultQuery")

    # student
    mainStudentExamResult(
        klase_id: Int!
        student_id: Int!
        term_id: Int!
        session_id: Int!
        status: String!
    ): [ExamRecord] @field(resolver: "ExamRecord\\MainStudentExamResultQuery")
}

extend type Mutation {
    updatePublishResult(
        status: String!
        klase_id: Int!
        term_id: Int!
        session_id: Int!
    ): ExamRecord @field(resolver: "ExamRecord\\PublishResultMutator")
}
