extend type Query {
    klases(slug: String): [Klase] @field(resolver: "Klase\\KlasesQuery")
    klasex: [Klase!]! @all
    klase(id: ID!, slug: String @eq): Klase
        @field(resolver: "Klase\\KlaseQuery")
}

extend type Mutation {
    createKlase(name: String!, workspace: String): Klase
        @field(resolver: "Klase\\CreateKlaseMutator")

    updateKlase(id: ID!, name: String!, workspace: String): Klase
        @field(resolver: "Klase\\UpdateKlaseMutator")

    deleteKlase(id: ID!): Klase @field(resolver: "Klase\\AssignKlaseToTeacher")

    # assign class to teacher
    assignKlaseToTeacher(klase: Int!, teacher: [Int!]): Klase
        @field(resolver: "Klase\\AssignKlaseToTeacher")
}
