extend type Query {
    klases: [Klase!]! @all
    klasex: [Klase!]! @all
    klase(id: ID! @eq): Klase @first
}

extend type Mutation {
    createKlase(name: String!): Klase @create

    updateKlase(id: ID!, name: String!): Klase @update

    deleteKlase(id: ID!): Klase @field(resolver: "Klase\\AssignKlaseToTeacher")

    # assign class to teacher
    assignKlaseToTeacher(klase: Int!, teacher: [Int!]): Klase
        @field(resolver: "Klase\\AssignKlaseToTeacher")
}
