extend type Query {
    libarians(workspaceId: Int): [Libarian!]!
        @field(resolver: "Libarian\\LibariansQuery")
    libarian(id: Int!, workspaceId: Int @eq): Libarian
        @field(resolver: "Libarian\\LibarianQuery")
}

extend type Mutation {
    createLibarian(
        workspaceId: Int
        userTable: UsersInput
        teacherTable: WorkersInput
    ): Libarian @field(resolver: "Libarian\\CreateLibarianMutator")

    updateLibarian(
        id: ID!
        workspaceId: Int
        userTable: UsersInput
        teacherTable: WorkersInput
    ): Libarian @field(resolver: "Libarian\\UpdateLibarianMutator")

    deleteLibarian(
        id: Int! @rules(apply: ["exists:libarians"])
        workspaceId: Int
    ): Boolean @field(resolver: "Libarian\\DeleteLibarianMutator")
}
