extend type Query{
       marks(
        "Filters by name. Accepts SQL LIKE wildcards `%` and `_`."
        klase_id: Int!, subject_id: Int! @where(operator: "like")
    ): [Mark!]! @all
}

extend type Mutation {
    updateMarks(marks: [MarkInput]): Mark
        @field(resolver: "Mark\\UpdateMarkMutator")
}
