extend type Query {
    notices(workspaceId: Int! @eq): [Notice!]!
        @field(resolver: "Notice\\NoticesQuery")

    schoolNotices(workspaceId: Int! @eq): [Notice!]!
        @field(resolver: "Notice\\SchoolNoticesQuery")

    notice(id: ID! @eq): Notice @find
}

extend type Mutation {
    createNotice(
        description: String @rules(apply: ["required"])
        date: String @rules(apply: ["required"])
        workspaceId: Int!
    ): Notice @field(resolver: "Notice\\CreateNoticeMutator")

    bulkDeleteNotice(workspaceId: Int!, ids: [String!]): Boolean
        @field(resolver: "Notice\\BulkDeleteNoticesMutator")

    updateNotice(
        id: ID!
        description: String @rules(apply: ["required"])
        date: String @rules(apply: ["required"])
        workspaceId: Int!
    ): Notice @field(resolver: "Notice\\UpdateNoticeMutator")

    deleteNotice(id: Int!, workspaceId: Int!): Notice
        @field(resolver: "Notice\\DeleteNoticeMutator")

    publishNotice(id: Int!, workspaceId: Int!): Notice
        @field(resolver: "Notice\\PublishNoticeMutator")
}
