extend type Query {
    promoteStudents(
        status: Boolean!
        klase_id: Int!
        session_id: Int!
        workspaceId: Int
        section_id: Int! @eq
    ): [Student] @field(resolver: "Promotion\\PromoteStudentsQuery")

    resetKlase(id: ID! @eq): Klase @first

    resetPromotion(
        status: Boolean!
        from_class: Int!
        from_term: Int!
        workspaceId: Int
        from_session: Int! @eq
    ): [Promotion] @field(resolver: "Promotion\\ResetPromoteQuery")

    setPromotion(workspaceId: Int): SetPromotion
        @field(resolver: "Promotion\\setPromotionQuery")
}

extend type Mutation {
    CreateSetPromotion(name: Int!, workspaceId: Int): SetPromotion
        @field(resolver: "SetPromotion\\setPromotionMutator")

    createPromoteStudents(
        klase_id: Int!
        klaseTo: Int!
        session_id: Int!
        sessionTo: Int!
        from_term: Int!
        workspaceId: Int
    ): [Student] @field(resolver: "Promotion\\PromoteStudents")

    createResetPromote(
        status: Boolean!
        from_class: Int!
        from_session: Int!
        from_term: Int!
        workspaceId: Int
    ): [Promotion] @field(resolver: "Promotion\\CreateResetPromotion")
}
