extend type Query {
    promoteStudents(
        status: Boolean!
        klase_id: Int!
        session_id: Int! @eq
    ): [Student] @field(resolver: "Promotion\\PromoteStudentsQuery")

    resetKlase(id: ID! @eq): Klase @first

    resetPromotion(
        status: Boolean!
        from_class: Int!
        from_term: Int!
        from_session: Int! @eq
    ): [Promotion] @field(resolver: "Promotion\\ResetPromoteQuery")

    setPromotion: [SetPromotion] @all
}

extend type Mutation {
    CreateSetPromotion(id: ID!, name: Int!): SetPromotion @update
    createPromoteStudents(
        klase_id: Int!
        klaseTo: Int!
        session_id: Int!
        sessionTo: Int!
        from_term: Int!
    ): [Student] @field(resolver: "Promotion\\PromoteStudents")

    createResetPromote(
        status: Boolean!
        from_class: Int!
        from_session: Int!
        from_term: Int!
    ): [Promotion] @field(resolver: "Promotion\\CreateResetPromotion")
}
