extend type Query {
    sessions(workspaceId: Int @eq): [Session!]!
        @field(resolver: "Session\\SessionsQuery")

    session(id: Int!, workspaceId: Int @eq): Session
        @field(resolver: "Session\\SessionQuery")
}

extend type Mutation {
    createSession(name: String!, workspaceId: Int): Session
        @field(resolver: "Session\\CreateSessionMutator")
    updateSession(id: ID!, name: String!, workspaceId: Int): Session
        @field(resolver: "Session\\UpdateSessionMutator")

    deleteSession(id: ID!): Session
        @field(resolver: "Session\\DeleteSessionMutator")
}
