extend type Query {
    students: [Student!]! @all
    student(slug: String! @eq): Student @first
    studentsDashboard: [Student!]! @all
}

extend type Mutation {
    createStudent(
        studentUser: StudentUserInput
        student: StudentInput
    ): Student @field(resolver: "Student\\CreateStudentMutator")

    updateStudent(
        id: ID!
        studentUser: EditStudentUserInput
        student: EditStudentInput
    ): Student @field(resolver: "Student\\UpdateStudentMutator")

     deleteStudent(
        id: Int! @rules(apply: ["exists:students"])
    ): Boolean @field(resolver: "Student\\DeleteStudentMutator")
}
