extend type Query {
    subjects(klase_id: Int!, workspaceId: Int, section_id: Int!): [Subject]
        @field(resolver: "Subject\\SubjectsQuery")
    subject(id: ID!, workspaceId: Int @eq): Subject
        @field(resolver: "Subject\\SubjectQuery")
}

extend type Mutation {
    createSubject(
        subject: String! @rules(apply: ["required"])
        subject_code: String! @rules(apply: ["required"])
        workspaceId: Int
        klase_id: Int
        section_id: Int!
    ): Subject @field(resolver: "Subject\\CreateSubjectMutator")

    updateSubject(
        id: ID!
        subject: String!
        subject_code: String!
        workspaceId: Int
    ): Subject @field(resolver: "Subject\\UpdateSubjectMutator")

    deleteSubject(id: ID!): Subject
        @field(resolver: "Subject\\DeleteSubjectMutator")
}
