extend type Query {
    subjects: [Subject!]! @all
    subject(id: ID! @eq): Subject @first
}

extend type Mutation {
    createSubject(subject: String!): Subject @create

    updateSubject(id: ID!, subject: String!): Subject @update

    deleteSubject(id: ID!): Subject
        @field(resolver: "Subject\\AssignSubjectToTeacher")

    # assign subject
    assignSubject(subjects: [Int!], teacher: Int!): Subject
        @field(resolver: "Subject\\AssignSubjectToTeacher")
}
