extend type Query {
    teachers(workspaceId: Int): [Teacher!]!
        @field(resolver: "Teacher\\TeachersQuery")

    teacher(id: Int!, workspaceId: Int @eq): Teacher
        @field(resolver: "Teacher\\TeacherQuery")

    teachersDashboard(workspaceId: Int): [Teacher!]!
        @field(resolver: "Teacher\\TeacherDashboardQuery")
}

extend type Mutation {
    createTeacher(
        workspaceId: Int
        userTable: UsersInput
        teacherTable: WorkersInput
    ): Teacher @field(resolver: "Teacher\\CreateTeacherMutator")

    updateTeacher(
        id: ID!
        workspaceId: Int
        userTable: EditUsersInput
        teacherTable: WorkersInput
    ): Teacher @field(resolver: "Teacher\\UpdateTeacherMutator")

    deleteTeacher(
        id: Int! 
        workspaceId: Int
    ): Boolean @field(resolver: "Teacher\\DeleteTeacherMutator")
}
