extend type Query {
    adminWorkspace(workspaceId: Int!, status: Int): Workspace
        @field(resolver: "Workspace\\WorkspaceQuery")

    schools: [Workspace!]! @all

    school(id: ID! @eq): Workspace @first
}

extend type Mutation {
    # createAdminWorkspace(
    #     workspaceId: Int!
    #     logo: Upload
    #         @rules(
    #             apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"]
    #         )
    #     stamp: Upload
    #         @rules(
    #             apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"]
    #         )
    #     paystack_secret_key: String
    #         @rules(apply: ["required", "unique:workspaces,paystack_secret_key"])
    #     email: String @rules(apply: ["required", "unique:workspaces,email"])
    #     status: Int
    # ): Workspace @field(resolver: "Workspace\\CreateAdminWorkspace")

    # updateAdminWorkspace(
    #     id: Int!
        # workspaceId: Int!
        # logo: Upload
        #     @rules(
        #         apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"]
        #     )
        # stamp: Upload
        #     @rules(
        #         apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"]
        #     )
        # paystack_secret_key: String
        #     @rules(apply: ["required", "unique:workspaces,paystack_secret_key"])
        # email: String @rules(apply: ["required", "unique:workspaces,email"])
        # status: Int
    # ): Workspace @field(resolver: "Workspace\\UpdateAdminWorkspace")

    createSchool(
        name: String!
        slug: String!
        email: String!
        first_name: String!
        last_name: String!
        phone: Int!
        lga: String
        country: Int!
        state: Int!
        city: Int!
    ): Boolean @field(resolver: "Workspace\\CreateSchoolWorkspace")

    updateSchool(
        id: Int!
        name: String!
        slug: String!
        email: String!
        first_name: String!
        last_name: String!
        phone: Int!
        lga: String
        country: Int!
        state: Int!
        city: Int!
    ): Workspace @field(resolver: "Workspace\\UpdateSchoolWorkspace")

    updateAdminSettings(
        workspaceId: ID!
        logo: Upload
            @rules(
                apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"]
            )
        stamp: Upload
            @rules(
                apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"]
            )
        paystack_secret_key: String
    ): Workspace @field(resolver: "Workspace\\UpdateAdminSettingsWorkspace")

    deleteSchool(workspaceId: Int!): Boolean
        @field(resolver: "Workspace\\DeleteSchoolWorkspace")
}
