extend type Query {
    userWorkspace(id: ID @eq): User @first

    workspaces: [Workspace!]! @all
    adminWorkspace(workspaceId: Int!, status: Int): Workspace
        @field(resolver: "Workspace\\WorkspaceQuery")

    schools: [Workspace!]! @field(resolver: "Workspace\\WorkspacesQuery")

    school(id: ID! @eq): Workspace @first
    numStudents: [Numstudent] @all
}

extend type Mutation {
    createSchool(
        name: String!
        slug: String!
        email: String! @rules(apply: ["required", "unique:users,email"])
        first_name: String!
        last_name: String!
        numStudentId: Int!
        phone: String! @rules(apply: ["required", "unique:users,phone"])
        lga: String
        gender: String!
        country: Int!
        state: Int!
        city: String!
        photo: Upload
            @rules(
                apply: ["required", "mimetypes:image/jpeg,image/png,image/jpg"]
            )
    ): Boolean @field(resolver: "Workspace\\CreateSchoolWorkspace")

    updateSchool(
        id: Int!
        name: String!
        slug: String!
        email: String!
        first_name: String!
        last_name: String!
        phone: String!
        numStudentId: Int!
        gender: String!
        lga: String
        country: Int!
        state: Int!
        city: String!
        photo: Upload
            @rules(
                apply: ["nullable", "mimetypes:image/jpeg,image/png,image/jpg"]
            )
    ): Workspace @field(resolver: "Workspace\\UpdateSchoolWorkspace")

    # setting
    updateAdminSettings(
        workspaceId: ID!
        bank: String
        account_name: String
        account_no: String
        logo: Upload
            @rules(
                apply: [
                    "nullable"
                    "mimetypes:image/jpeg,image/png,image/jpg,image/svg+xml"
                ]
            )
        stamp: Upload
            @rules(
                apply: [
                    "nullable"
                    "mimetypes:image/jpeg,image/png,image/jpg,image/svg+xml"
                ]
            )
        paystack_secret_key: String
    ): Workspace @field(resolver: "Workspace\\UpdateAdminSettingsWorkspace")

    SuspendSchool(workspaceId: ID!, status: Int!): Workspace
        @field(resolver: "Workspace\\SuspendSchoolWorkspace")

    deleteSchool(workspaceId: Int!): Boolean
        @field(resolver: "Workspace\\DeleteSchoolWorkspace")
}
